use std::collections::BTreeMap;
use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

struct Registry<'a> {
    module: &'a str,
    file: &'a str,
    name_column: &'a str,
}

const REGISTRIES: [Registry<'static>; 4] = [
    Registry {
        module: "frame",
        file: "iana-http3-frame-types.csv",
        name_column: "Frame Type",
    },
    Registry {
        module: "setting",
        file: "iana-http3-settings.csv",
        name_column: "Setting Name",
    },
    Registry {
        module: "error",
        file: "iana-http3-error-codes.csv",
        name_column: "Name",
    },
    Registry {
        module: "stream",
        file: "iana-http3-stream-types.csv",
        name_column: "Stream Type",
    },
];

fn main() -> Result<(), Box<dyn Error>> {
    let mut args = env::args_os().skip(1);
    let snapshot = PathBuf::from(args.next().ok_or("missing snapshot directory")?);
    let output = PathBuf::from(args.next().ok_or("missing output path")?);
    if args.next().is_some() {
        return Err("usage: nghttp3-specgen <snapshot-dir> <output.rs>".into());
    }

    let mut rust = String::from(
        "// @generated by nghttp3-specgen from the IANA HTTP/3 registries.\n\
         // Do not edit by hand.\n\n",
    );

    for registry in REGISTRIES {
        let entries = read_registry(&snapshot.join(registry.file), registry.name_column)?;
        writeln!(rust, "/// {}.", module_doc(registry.module))?;
        writeln!(rust, "pub mod {} {{", registry.module)?;
        for (value, name) in entries {
            writeln!(rust, "    pub const {}: u64 = {value:#x};", rust_ident(&name))?;
        }
        rust.push_str("}\n\n");
    }

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output, rust)?;
    Ok(())
}

fn read_registry(path: &Path, name_column: &str) -> Result<BTreeMap<u64, String>, Box<dyn Error>> {
    let mut reader = csv::Reader::from_path(path)?;
    let headers = reader.headers()?.clone();
    let value_idx = headers
        .iter()
        .position(|header| header == "Value")
        .ok_or("IANA registry lacks Value column")?;
    let name_idx = headers
        .iter()
        .position(|header| header == name_column)
        .ok_or("IANA registry lacks expected name column")?;
    let status_idx = headers
        .iter()
        .position(|header| header == "Status")
        .ok_or("IANA registry lacks Status column")?;

    let mut result = BTreeMap::new();
    for row in reader.records() {
        let row = row?;
        if row.get(status_idx) != Some("permanent") {
            continue;
        }
        let Some(value) = row.get(value_idx).and_then(parse_single_hex) else {
            continue;
        };
        let Some(name) = row.get(name_idx) else {
            continue;
        };
        result.insert(value, name.to_owned());
    }
    Ok(result)
}

fn parse_single_hex(value: &str) -> Option<u64> {
    if value.contains('-') {
        return None;
    }
    value
        .strip_prefix("0x")
        .and_then(|hex| u64::from_str_radix(hex, 16).ok())
}

fn rust_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut underscore = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            if underscore && !out.is_empty() {
                out.push('_');
            }
            out.push(ch.to_ascii_uppercase());
            underscore = false;
        } else {
            underscore = true;
        }
    }
    out.trim_matches('_').to_owned()
}

const fn module_doc(module: &str) -> &'static str {
    match module {
        "frame" => "HTTP/3 frame type code points",
        "setting" => "HTTP/3 setting identifiers",
        "error" => "HTTP/3 and QPACK application error codes",
        "stream" => "HTTP/3 unidirectional stream type code points",
        _ => "HTTP/3 registry",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_ranges_and_normalizes_names() {
        assert_eq!(parse_single_hex("0x0f"), Some(15));
        assert_eq!(parse_single_hex("0x0f-0x10"), None);
        assert_eq!(rust_ident("QPACK Encoder Stream"), "QPACK_ENCODER_STREAM");
        assert_eq!(rust_ident("SETTINGS-H3 DATAGRAM"), "SETTINGS_H3_DATAGRAM");
    }
}
